services:
  dotfiles:
    build:
      args:
        - USER=$USER
        - GID=$G
        - UID=$U
        - PASS=0000
        - UBUNTU_CODENAME=${UBUNTU_CODENAME:-noble}
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - ${SSH_PORT:-2222}:${SSH_PORT:-2222}
    environment:
      - SSH_PORT=${SSH_PORT:-2222}
    volumes:
      - ./container-disk:/home/$USER/host-disk
      - ..:/home/$USER/.local/share/dotfiles:ro
    privileged: true
    tty: true
